### ISSUE TITLE
[meta] TLS test suite

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/bertie#7]
- [x] self test (client-server)
- [x] manual interop (e.g. openssl server + bertie client, bertie server + openssl client)
- [x] interop framework
  * [x] #30 (not useful for interop)
  * [x] #31 (not useful for interop)
  * [x] #48 (not useful for interop)
  * [x] #49 (not useful for interop)
- [x] tls test vectors (e.g. https://datatracker.ietf.org/doc/html/rfc8448)
